In [23]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.drop(columns=['alive','class','who','adult_male','deck','fare','embark_town'],inplace=True)

In [5]:
df.head()

   survived  pclass     sex   age  sibsp  parch embarked  alone
0         0       3    male  22.0      1      0        S  False
1         1       1  female  38.0      1      0        C  False
2         1       3  female  26.0      0      0        S   True
3         1       1  female  35.0      1      0        S  False
4         0       3    male  35.0      0      0        S   True

In [6]:
df.isna().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
embarked      2
alone         0
dtype: int64

In [7]:
df['age'] = df.groupby(['pclass','sex'])['age'].transform(lambda x: x.fillna(x.median()))

In [12]:
df.dropna(inplace=True)

In [13]:
df.duplicated().sum()

np.int64(318)

In [15]:
df = pd.get_dummies(df,columns=['embarked','sex'],drop_first=True)

In [17]:
df['alone'] = df['alone'].astype(int)

In [ ]:
df = df.replace({True:1, False:0})

In [21]:
df.head()

,survived,pclass,age,sibsp,parch,alone,embarked_Q,embarked_S,sex_male
0,0,3,22.0,1,0,0,0,1,1
1,1,1,38.0,1,0,0,0,0,0
2,1,3,26.0,0,0,1,0,1,0
3,1,1,35.0,1,0,0,0,1,0
4,0,3,35.0,0,0,1,0,1,1

In [22]:
x = df.iloc[: , 1:9]
y = df.iloc[: , 0]

In [24]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y, test_size=.2,random_state=42)

In [ ]:
xtrain.to_csv('xtrain.csv', index=False)
xtest.to_csv('xtest.csv', index=False)
ytrain.to_csv('ytrain.csv',index=False)
ytest.to_csv('ytest.csv',index=False)